### ISSUE TITLE
VSCode: Lightning component compilation errors do not show

### ISSUE THREAD

**Issue by dsharrison** [joeferraro/MavensMate#830]
* **MavensMate Desktop Version**: v0.0.11-beta.6

* **Editor**: Visual Studio Code

* **MavensMate Plugin Version**: 0.6.1

* **Platform/Version**: macOS Sierra 10.12

* **Proxy Details**: None

* **Salesforce API Version**: 37

* **Salesforce Server**: na35

**Details** 
When an aura component fails to compile, the compile is reported as a success in the editor and no feedback is given. To reproduce this, simply introduce any bad markup to a `*.cmp` file such as `<ltng:spoof />` and save the file.

**Expected**
A compile error is presented with the error detail (in this case no such component found for <ltng:spoof>.

**Actual**
Compile File: Starting
Compile File: Finished

No error is shown.

Let me know if you need any additional details.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/196929402075618/210822620795830)

**Comment by kidtsunami** [comment]
Resolved in https://github.com/kidtsunami/MavensMate-VisualStudioCode/commit/3d3a24c2c892b57e298d643ff122e05805730494

This should work in v0.10.0 of MavensMate for VS Code

Thank you @dsharrison for raising this issue, and deepest apologies that it was not resolved sooner!
